DISTFILES += \
    ../ssd-caffe/src/caffe/test/test_data/sample_data.h5 \
    ../ssd-caffe/src/caffe/test/test_data/sample_data_2_gzip.h5 \
    ../ssd-caffe/src/caffe/test/test_data/solver_data.h5 \
    ../ssd-caffe/src/caffe/proto/caffe.proto \
    ../ssd-caffe/src/caffe/test/test_data/sample_data_list.txt \
    ../ssd-caffe/src/caffe/test/test_data/solver_data_list.txt \
    ../ssd-caffe/src/caffe/layers/absval_layer.cu \
    ../ssd-caffe/src/caffe/layers/base_data_layer.cu \
    ../ssd-caffe/src/caffe/layers/batch_norm_layer.cu \
    ../ssd-caffe/src/caffe/layers/batch_reindex_layer.cu \
    ../ssd-caffe/src/caffe/layers/bias_layer.cu \
    ../ssd-caffe/src/caffe/layers/bnll_layer.cu \
    ../ssd-caffe/src/caffe/layers/concat_layer.cu \
    ../ssd-caffe/src/caffe/layers/contrastive_loss_layer.cu \
    ../ssd-caffe/src/caffe/layers/conv_layer.cu \
    ../ssd-caffe/src/caffe/layers/crop_layer.cu \
    ../ssd-caffe/src/caffe/layers/cudnn_conv_layer.cu \
    ../ssd-caffe/src/caffe/layers/cudnn_lcn_layer.cu \
    ../ssd-caffe/src/caffe/layers/cudnn_lrn_layer.cu \
    ../ssd-caffe/src/caffe/layers/cudnn_pooling_layer.cu \
    ../ssd-caffe/src/caffe/layers/cudnn_relu_layer.cu \
    ../ssd-caffe/src/caffe/layers/cudnn_sigmoid_layer.cu \
    ../ssd-caffe/src/caffe/layers/cudnn_softmax_layer.cu \
    ../ssd-caffe/src/caffe/layers/cudnn_tanh_layer.cu \
    ../ssd-caffe/src/caffe/layers/deconv_layer.cu \
    ../ssd-caffe/src/caffe/layers/detection_output_layer.cu \
    ../ssd-caffe/src/caffe/layers/dropout_layer.cu \
    ../ssd-caffe/src/caffe/layers/eltwise_layer.cu \
    ../ssd-caffe/src/caffe/layers/elu_layer.cu \
    ../ssd-caffe/src/caffe/layers/embed_layer.cu \
    ../ssd-caffe/src/caffe/layers/euclidean_loss_layer.cu \
    ../ssd-caffe/src/caffe/layers/exp_layer.cu \
    ../ssd-caffe/src/caffe/layers/filter_layer.cu \
    ../ssd-caffe/src/caffe/layers/hdf5_data_layer.cu \
    ../ssd-caffe/src/caffe/layers/hdf5_output_layer.cu \
    ../ssd-caffe/src/caffe/layers/im2col_layer.cu \
    ../ssd-caffe/src/caffe/layers/inner_product_layer.cu \
    ../ssd-caffe/src/caffe/layers/log_layer.cu \
    ../ssd-caffe/src/caffe/layers/lrn_layer.cu \
    ../ssd-caffe/src/caffe/layers/lstm_unit_layer.cu \
    ../ssd-caffe/src/caffe/layers/mvn_layer.cu \
    ../ssd-caffe/src/caffe/layers/normalize_layer.cu \
    ../ssd-caffe/src/caffe/layers/permute_layer.cu \
    ../ssd-caffe/src/caffe/layers/pooling_layer.cu \
    ../ssd-caffe/src/caffe/layers/power_layer.cu \
    ../ssd-caffe/src/caffe/layers/prelu_layer.cu \
    ../ssd-caffe/src/caffe/layers/recurrent_layer.cu \
    ../ssd-caffe/src/caffe/layers/reduction_layer.cu \
    ../ssd-caffe/src/caffe/layers/relu_layer.cu \
    ../ssd-caffe/src/caffe/layers/scale_layer.cu \
    ../ssd-caffe/src/caffe/layers/sigmoid_cross_entropy_loss_layer.cu \
    ../ssd-caffe/src/caffe/layers/sigmoid_layer.cu \
    ../ssd-caffe/src/caffe/layers/silence_layer.cu \
    ../ssd-caffe/src/caffe/layers/slice_layer.cu \
    ../ssd-caffe/src/caffe/layers/smooth_L1_loss_layer.cu \
    ../ssd-caffe/src/caffe/layers/softmax_layer.cu \
    ../ssd-caffe/src/caffe/layers/softmax_loss_layer.cu \
    ../ssd-caffe/src/caffe/layers/split_layer.cu \
    ../ssd-caffe/src/caffe/layers/tanh_layer.cu \
    ../ssd-caffe/src/caffe/layers/threshold_layer.cu \
    ../ssd-caffe/src/caffe/layers/tile_layer.cu \
    ../ssd-caffe/src/caffe/solvers/adadelta_solver.cu \
    ../ssd-caffe/src/caffe/solvers/adagrad_solver.cu \
    ../ssd-caffe/src/caffe/solvers/adam_solver.cu \
    ../ssd-caffe/src/caffe/solvers/nesterov_solver.cu \
    ../ssd-caffe/src/caffe/solvers/rmsprop_solver.cu \
    ../ssd-caffe/src/caffe/solvers/sgd_solver.cu \
    ../ssd-caffe/src/caffe/test/test_im2col_kernel.cu \
    ../ssd-caffe/src/caffe/util/bbox_util.cu \
    ../ssd-caffe/src/caffe/util/im2col.cu \
    ../ssd-caffe/src/caffe/util/math_functions.cu \
    ../ssd-caffe/src/caffe/test/CMakeLists.txt \
    ../ssd-caffe/src/caffe/CMakeLists.txt \
    ../ssd-caffe/src/gtest/CMakeLists.txt \
    ../ssd-caffe/src/caffe/test/test_data/generate_sample_data.py \
    ../ssd-caffe/tools/extra/launch_resize_and_crop_images.sh \
    ../ssd-caffe/tools/extra/parse_log.sh \
    ../ssd-caffe/tools/extra/plot_log.gnuplot.example \
    ../ssd-caffe/tools/CMakeLists.txt \
    ../ssd-caffe/tools/extra/extract_seconds.py \
    ../ssd-caffe/tools/extra/parse_log.py \
    ../ssd-caffe/tools/extra/plot_training_log.py.example \
    ../ssd-caffe/tools/extra/resize_and_crop_images.py \
    ../ssd-caffe/tools/extra/summarize.py

HEADERS += \
    ../ssd-caffe/include/caffe/layers/absval_layer.hpp \
    ../ssd-caffe/include/caffe/layers/accuracy_layer.hpp \
    ../ssd-caffe/include/caffe/layers/annotated_data_layer.hpp \
    ../ssd-caffe/include/caffe/layers/argmax_layer.hpp \
    ../ssd-caffe/include/caffe/layers/base_conv_layer.hpp \
    ../ssd-caffe/include/caffe/layers/base_data_layer.hpp \
    ../ssd-caffe/include/caffe/layers/batch_norm_layer.hpp \
    ../ssd-caffe/include/caffe/layers/batch_reindex_layer.hpp \
    ../ssd-caffe/include/caffe/layers/bias_layer.hpp \
    ../ssd-caffe/include/caffe/layers/bnll_layer.hpp \
    ../ssd-caffe/include/caffe/layers/concat_layer.hpp \
    ../ssd-caffe/include/caffe/layers/contrastive_loss_layer.hpp \
    ../ssd-caffe/include/caffe/layers/conv_layer.hpp \
    ../ssd-caffe/include/caffe/layers/crop_layer.hpp \
    ../ssd-caffe/include/caffe/layers/cudnn_conv_layer.hpp \
    ../ssd-caffe/include/caffe/layers/cudnn_lcn_layer.hpp \
    ../ssd-caffe/include/caffe/layers/cudnn_lrn_layer.hpp \
    ../ssd-caffe/include/caffe/layers/cudnn_pooling_layer.hpp \
    ../ssd-caffe/include/caffe/layers/cudnn_relu_layer.hpp \
    ../ssd-caffe/include/caffe/layers/cudnn_sigmoid_layer.hpp \
    ../ssd-caffe/include/caffe/layers/cudnn_softmax_layer.hpp \
    ../ssd-caffe/include/caffe/layers/cudnn_tanh_layer.hpp \
    ../ssd-caffe/include/caffe/layers/data_layer.hpp \
    ../ssd-caffe/include/caffe/layers/deconv_layer.hpp \
    ../ssd-caffe/include/caffe/layers/detection_evaluate_layer.hpp \
    ../ssd-caffe/include/caffe/layers/detection_output_layer.hpp \
    ../ssd-caffe/include/caffe/layers/dropout_layer.hpp \
    ../ssd-caffe/include/caffe/layers/dummy_data_layer.hpp \
    ../ssd-caffe/include/caffe/layers/eltwise_layer.hpp \
    ../ssd-caffe/include/caffe/layers/elu_layer.hpp \
    ../ssd-caffe/include/caffe/layers/embed_layer.hpp \
    ../ssd-caffe/include/caffe/layers/euclidean_loss_layer.hpp \
    ../ssd-caffe/include/caffe/layers/exp_layer.hpp \
    ../ssd-caffe/include/caffe/layers/filter_layer.hpp \
    ../ssd-caffe/include/caffe/layers/flatten_layer.hpp \
    ../ssd-caffe/include/caffe/layers/hdf5_data_layer.hpp \
    ../ssd-caffe/include/caffe/layers/hdf5_output_layer.hpp \
    ../ssd-caffe/include/caffe/layers/hinge_loss_layer.hpp \
    ../ssd-caffe/include/caffe/layers/im2col_layer.hpp \
    ../ssd-caffe/include/caffe/layers/image_data_layer.hpp \
    ../ssd-caffe/include/caffe/layers/infogain_loss_layer.hpp \
    ../ssd-caffe/include/caffe/layers/inner_product_layer.hpp \
    ../ssd-caffe/include/caffe/layers/input_layer.hpp \
    ../ssd-caffe/include/caffe/layers/log_layer.hpp \
    ../ssd-caffe/include/caffe/layers/loss_layer.hpp \
    ../ssd-caffe/include/caffe/layers/lrn_layer.hpp \
    ../ssd-caffe/include/caffe/layers/lstm_layer.hpp \
    ../ssd-caffe/include/caffe/layers/memory_data_layer.hpp \
    ../ssd-caffe/include/caffe/layers/multibox_loss_layer.hpp \
    ../ssd-caffe/include/caffe/layers/multinomial_logistic_loss_layer.hpp \
    ../ssd-caffe/include/caffe/layers/mvn_layer.hpp \
    ../ssd-caffe/include/caffe/layers/neuron_layer.hpp \
    ../ssd-caffe/include/caffe/layers/normalize_layer.hpp \
    ../ssd-caffe/include/caffe/layers/parameter_layer.hpp \
    ../ssd-caffe/include/caffe/layers/permute_layer.hpp \
    ../ssd-caffe/include/caffe/layers/pooling_layer.hpp \
    ../ssd-caffe/include/caffe/layers/power_layer.hpp \
    ../ssd-caffe/include/caffe/layers/prelu_layer.hpp \
    ../ssd-caffe/include/caffe/layers/prior_box_layer.hpp \
    ../ssd-caffe/include/caffe/layers/python_layer.hpp \
    ../ssd-caffe/include/caffe/layers/recurrent_layer.hpp \
    ../ssd-caffe/include/caffe/layers/reduction_layer.hpp \
    ../ssd-caffe/include/caffe/layers/relu_layer.hpp \
    ../ssd-caffe/include/caffe/layers/reshape_layer.hpp \
    ../ssd-caffe/include/caffe/layers/rnn_layer.hpp \
    ../ssd-caffe/include/caffe/layers/scale_layer.hpp \
    ../ssd-caffe/include/caffe/layers/sigmoid_cross_entropy_loss_layer.hpp \
    ../ssd-caffe/include/caffe/layers/sigmoid_layer.hpp \
    ../ssd-caffe/include/caffe/layers/silence_layer.hpp \
    ../ssd-caffe/include/caffe/layers/slice_layer.hpp \
    ../ssd-caffe/include/caffe/layers/smooth_L1_loss_layer.hpp \
    ../ssd-caffe/include/caffe/layers/softmax_layer.hpp \
    ../ssd-caffe/include/caffe/layers/softmax_loss_layer.hpp \
    ../ssd-caffe/include/caffe/layers/split_layer.hpp \
    ../ssd-caffe/include/caffe/layers/spp_layer.hpp \
    ../ssd-caffe/include/caffe/layers/tanh_layer.hpp \
    ../ssd-caffe/include/caffe/layers/threshold_layer.hpp \
    ../ssd-caffe/include/caffe/layers/tile_layer.hpp \
    ../ssd-caffe/include/caffe/layers/video_data_layer.hpp \
    ../ssd-caffe/include/caffe/layers/window_data_layer.hpp \
    ../ssd-caffe/include/caffe/test/test_caffe_main.hpp \
    ../ssd-caffe/include/caffe/test/test_gradient_check_util.hpp \
    ../ssd-caffe/include/caffe/util/bbox_util.hpp \
    ../ssd-caffe/include/caffe/util/benchmark.hpp \
    ../ssd-caffe/include/caffe/util/blocking_queue.hpp \
    ../ssd-caffe/include/caffe/util/cudnn.hpp \
    ../ssd-caffe/include/caffe/util/db.hpp \
    ../ssd-caffe/include/caffe/util/db_leveldb.hpp \
    ../ssd-caffe/include/caffe/util/db_lmdb.hpp \
    ../ssd-caffe/include/caffe/util/device_alternate.hpp \
    ../ssd-caffe/include/caffe/util/format.hpp \
    ../ssd-caffe/include/caffe/util/gpu_util.cuh \
    ../ssd-caffe/include/caffe/util/hdf5.hpp \
    ../ssd-caffe/include/caffe/util/im2col.hpp \
    ../ssd-caffe/include/caffe/util/im_transforms.hpp \
    ../ssd-caffe/include/caffe/util/insert_splits.hpp \
    ../ssd-caffe/include/caffe/util/io.hpp \
    ../ssd-caffe/include/caffe/util/math_functions.hpp \
    ../ssd-caffe/include/caffe/util/mkl_alternate.hpp \
    ../ssd-caffe/include/caffe/util/old-version-cudnn.hpp \
    ../ssd-caffe/include/caffe/util/rng.hpp \
    ../ssd-caffe/include/caffe/util/sampler.hpp \
    ../ssd-caffe/include/caffe/util/signal_handler.h \
    ../ssd-caffe/include/caffe/util/upgrade_proto.hpp \
    ../ssd-caffe/include/caffe/blob.hpp \
    ../ssd-caffe/include/caffe/caffe.hpp \
    ../ssd-caffe/include/caffe/common.hpp \
    ../ssd-caffe/include/caffe/data_reader.hpp \
    ../ssd-caffe/include/caffe/data_transformer.hpp \
    ../ssd-caffe/include/caffe/filler.hpp \
    ../ssd-caffe/include/caffe/internal_thread.hpp \
    ../ssd-caffe/include/caffe/layer.hpp \
    ../ssd-caffe/include/caffe/layer_factory.hpp \
    ../ssd-caffe/include/caffe/net.hpp \
    ../ssd-caffe/include/caffe/parallel.hpp \
    ../ssd-caffe/include/caffe/sgd_solvers.hpp \
    ../ssd-caffe/include/caffe/solver.hpp \
    ../ssd-caffe/include/caffe/solver_factory.hpp \
    ../ssd-caffe/include/caffe/syncedmem.hpp \
    ../ssd-caffe/src/gtest/gtest.h \
    ../ssd-caffe/include/caffe/proto/caffe.pb.h

SOURCES += \
    ../ssd-caffe/src/caffe/layers/absval_layer.cpp \
    ../ssd-caffe/src/caffe/layers/accuracy_layer.cpp \
    ../ssd-caffe/src/caffe/layers/annotated_data_layer.cpp \
    ../ssd-caffe/src/caffe/layers/argmax_layer.cpp \
    ../ssd-caffe/src/caffe/layers/base_conv_layer.cpp \
    ../ssd-caffe/src/caffe/layers/base_data_layer.cpp \
    ../ssd-caffe/src/caffe/layers/batch_norm_layer.cpp \
    ../ssd-caffe/src/caffe/layers/batch_reindex_layer.cpp \
    ../ssd-caffe/src/caffe/layers/bias_layer.cpp \
    ../ssd-caffe/src/caffe/layers/bnll_layer.cpp \
    ../ssd-caffe/src/caffe/layers/concat_layer.cpp \
    ../ssd-caffe/src/caffe/layers/contrastive_loss_layer.cpp \
    ../ssd-caffe/src/caffe/layers/conv_layer.cpp \
    ../ssd-caffe/src/caffe/layers/crop_layer.cpp \
    ../ssd-caffe/src/caffe/layers/cudnn_conv_layer.cpp \
    ../ssd-caffe/src/caffe/layers/cudnn_lcn_layer.cpp \
    ../ssd-caffe/src/caffe/layers/cudnn_lrn_layer.cpp \
    ../ssd-caffe/src/caffe/layers/cudnn_pooling_layer.cpp \
    ../ssd-caffe/src/caffe/layers/cudnn_relu_layer.cpp \
    ../ssd-caffe/src/caffe/layers/cudnn_sigmoid_layer.cpp \
    ../ssd-caffe/src/caffe/layers/cudnn_softmax_layer.cpp \
    ../ssd-caffe/src/caffe/layers/cudnn_tanh_layer.cpp \
    ../ssd-caffe/src/caffe/layers/data_layer.cpp \
    ../ssd-caffe/src/caffe/layers/deconv_layer.cpp \
    ../ssd-caffe/src/caffe/layers/detection_evaluate_layer.cpp \
    ../ssd-caffe/src/caffe/layers/detection_output_layer.cpp \
    ../ssd-caffe/src/caffe/layers/dropout_layer.cpp \
    ../ssd-caffe/src/caffe/layers/dummy_data_layer.cpp \
    ../ssd-caffe/src/caffe/layers/eltwise_layer.cpp \
    ../ssd-caffe/src/caffe/layers/elu_layer.cpp \
    ../ssd-caffe/src/caffe/layers/embed_layer.cpp \
    ../ssd-caffe/src/caffe/layers/euclidean_loss_layer.cpp \
    ../ssd-caffe/src/caffe/layers/exp_layer.cpp \
    ../ssd-caffe/src/caffe/layers/filter_layer.cpp \
    ../ssd-caffe/src/caffe/layers/flatten_layer.cpp \
    ../ssd-caffe/src/caffe/layers/hdf5_data_layer.cpp \
    ../ssd-caffe/src/caffe/layers/hdf5_output_layer.cpp \
    ../ssd-caffe/src/caffe/layers/hinge_loss_layer.cpp \
    ../ssd-caffe/src/caffe/layers/im2col_layer.cpp \
    ../ssd-caffe/src/caffe/layers/image_data_layer.cpp \
    ../ssd-caffe/src/caffe/layers/infogain_loss_layer.cpp \
    ../ssd-caffe/src/caffe/layers/inner_product_layer.cpp \
    ../ssd-caffe/src/caffe/layers/input_layer.cpp \
    ../ssd-caffe/src/caffe/layers/log_layer.cpp \
    ../ssd-caffe/src/caffe/layers/loss_layer.cpp \
    ../ssd-caffe/src/caffe/layers/lrn_layer.cpp \
    ../ssd-caffe/src/caffe/layers/lstm_layer.cpp \
    ../ssd-caffe/src/caffe/layers/lstm_unit_layer.cpp \
    ../ssd-caffe/src/caffe/layers/memory_data_layer.cpp \
    ../ssd-caffe/src/caffe/layers/multibox_loss_layer.cpp \
    ../ssd-caffe/src/caffe/layers/multinomial_logistic_loss_layer.cpp \
    ../ssd-caffe/src/caffe/layers/mvn_layer.cpp \
    ../ssd-caffe/src/caffe/layers/neuron_layer.cpp \
    ../ssd-caffe/src/caffe/layers/normalize_layer.cpp \
    ../ssd-caffe/src/caffe/layers/parameter_layer.cpp \
    ../ssd-caffe/src/caffe/layers/permute_layer.cpp \
    ../ssd-caffe/src/caffe/layers/pooling_layer.cpp \
    ../ssd-caffe/src/caffe/layers/power_layer.cpp \
    ../ssd-caffe/src/caffe/layers/prelu_layer.cpp \
    ../ssd-caffe/src/caffe/layers/prior_box_layer.cpp \
    ../ssd-caffe/src/caffe/layers/recurrent_layer.cpp \
    ../ssd-caffe/src/caffe/layers/reduction_layer.cpp \
    ../ssd-caffe/src/caffe/layers/relu_layer.cpp \
    ../ssd-caffe/src/caffe/layers/reshape_layer.cpp \
    ../ssd-caffe/src/caffe/layers/rnn_layer.cpp \
    ../ssd-caffe/src/caffe/layers/scale_layer.cpp \
    ../ssd-caffe/src/caffe/layers/sigmoid_cross_entropy_loss_layer.cpp \
    ../ssd-caffe/src/caffe/layers/sigmoid_layer.cpp \
    ../ssd-caffe/src/caffe/layers/silence_layer.cpp \
    ../ssd-caffe/src/caffe/layers/slice_layer.cpp \
    ../ssd-caffe/src/caffe/layers/smooth_L1_loss_layer.cpp \
    ../ssd-caffe/src/caffe/layers/softmax_layer.cpp \
    ../ssd-caffe/src/caffe/layers/softmax_loss_layer.cpp \
    ../ssd-caffe/src/caffe/layers/split_layer.cpp \
    ../ssd-caffe/src/caffe/layers/spp_layer.cpp \
    ../ssd-caffe/src/caffe/layers/tanh_layer.cpp \
    ../ssd-caffe/src/caffe/layers/threshold_layer.cpp \
    ../ssd-caffe/src/caffe/layers/tile_layer.cpp \
    ../ssd-caffe/src/caffe/layers/video_data_layer.cpp \
    ../ssd-caffe/src/caffe/layers/window_data_layer.cpp \
    ../ssd-caffe/src/caffe/solvers/adadelta_solver.cpp \
    ../ssd-caffe/src/caffe/solvers/adagrad_solver.cpp \
    ../ssd-caffe/src/caffe/solvers/adam_solver.cpp \
    ../ssd-caffe/src/caffe/solvers/nesterov_solver.cpp \
    ../ssd-caffe/src/caffe/solvers/rmsprop_solver.cpp \
    ../ssd-caffe/src/caffe/solvers/sgd_solver.cpp \
    ../ssd-caffe/src/caffe/test/test_accuracy_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_annotated_data_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_argmax_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_batch_norm_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_batch_reindex_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_bbox_util.cpp \
    ../ssd-caffe/src/caffe/test/test_benchmark.cpp \
    ../ssd-caffe/src/caffe/test/test_bias_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_blob.cpp \
    ../ssd-caffe/src/caffe/test/test_caffe_main.cpp \
    ../ssd-caffe/src/caffe/test/test_common.cpp \
    ../ssd-caffe/src/caffe/test/test_concat_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_contrastive_loss_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_convolution_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_crop_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_data_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_data_transformer.cpp \
    ../ssd-caffe/src/caffe/test/test_db.cpp \
    ../ssd-caffe/src/caffe/test/test_deconvolution_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_detection_evaluate_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_detection_output_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_dummy_data_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_eltwise_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_embed_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_euclidean_loss_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_filler.cpp \
    ../ssd-caffe/src/caffe/test/test_filter_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_flatten_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_gradient_based_solver.cpp \
    ../ssd-caffe/src/caffe/test/test_hdf5_output_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_hdf5data_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_hinge_loss_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_im2col_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_im_transforms.cpp \
    ../ssd-caffe/src/caffe/test/test_image_data_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_infogain_loss_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_inner_product_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_internal_thread.cpp \
    ../ssd-caffe/src/caffe/test/test_io.cpp \
    ../ssd-caffe/src/caffe/test/test_layer_factory.cpp \
    ../ssd-caffe/src/caffe/test/test_lrn_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_lstm_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_math_functions.cpp \
    ../ssd-caffe/src/caffe/test/test_maxpool_dropout_layers.cpp \
    ../ssd-caffe/src/caffe/test/test_memory_data_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_multibox_loss_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_multinomial_logistic_loss_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_mvn_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_net.cpp \
    ../ssd-caffe/src/caffe/test/test_neuron_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_normalize_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_permute_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_platform.cpp \
    ../ssd-caffe/src/caffe/test/test_pooling_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_power_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_prior_box_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_protobuf.cpp \
    ../ssd-caffe/src/caffe/test/test_random_number_generator.cpp \
    ../ssd-caffe/src/caffe/test/test_reduction_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_reshape_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_rnn_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_scale_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_sigmoid_cross_entropy_loss_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_slice_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_smooth_L1_loss_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_softmax_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_softmax_with_loss_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_solver.cpp \
    ../ssd-caffe/src/caffe/test/test_solver_factory.cpp \
    ../ssd-caffe/src/caffe/test/test_split_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_spp_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_stochastic_pooling.cpp \
    ../ssd-caffe/src/caffe/test/test_syncedmem.cpp \
    ../ssd-caffe/src/caffe/test/test_tanh_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_threshold_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_tile_layer.cpp \
    ../ssd-caffe/src/caffe/test/test_upgrade_proto.cpp \
    ../ssd-caffe/src/caffe/test/test_util_blas.cpp \
    ../ssd-caffe/src/caffe/util/bbox_util.cpp \
    ../ssd-caffe/src/caffe/util/benchmark.cpp \
    ../ssd-caffe/src/caffe/util/blocking_queue.cpp \
    ../ssd-caffe/src/caffe/util/cudnn.cpp \
    ../ssd-caffe/src/caffe/util/db.cpp \
    ../ssd-caffe/src/caffe/util/db_leveldb.cpp \
    ../ssd-caffe/src/caffe/util/db_lmdb.cpp \
    ../ssd-caffe/src/caffe/util/hdf5.cpp \
    ../ssd-caffe/src/caffe/util/im2col.cpp \
    ../ssd-caffe/src/caffe/util/im_transforms.cpp \
    ../ssd-caffe/src/caffe/util/insert_splits.cpp \
    ../ssd-caffe/src/caffe/util/io.cpp \
    ../ssd-caffe/src/caffe/util/math_functions.cpp \
    ../ssd-caffe/src/caffe/util/sampler.cpp \
    ../ssd-caffe/src/caffe/util/signal_handler.cpp \
    ../ssd-caffe/src/caffe/util/upgrade_proto.cpp \
    ../ssd-caffe/src/caffe/blob.cpp \
    ../ssd-caffe/src/caffe/common.cpp \
    ../ssd-caffe/src/caffe/data_reader.cpp \
    ../ssd-caffe/src/caffe/data_transformer.cpp \
    ../ssd-caffe/src/caffe/internal_thread.cpp \
    ../ssd-caffe/src/caffe/layer.cpp \
    ../ssd-caffe/src/caffe/layer_factory.cpp \
    ../ssd-caffe/src/caffe/net.cpp \
    ../ssd-caffe/src/caffe/parallel.cpp \
    ../ssd-caffe/src/caffe/solver.cpp \
    ../ssd-caffe/src/caffe/syncedmem.cpp \
    ../ssd-caffe/src/gtest/gtest-all.cpp \
    ../ssd-caffe/src/gtest/gtest_main.cc \
    ../ssd-caffe/include/caffe/proto/caffe.pb.cc \
    ../ssd-caffe/tools/caffe.cpp \
    ../ssd-caffe/tools/compute_image_mean.cpp \
    ../ssd-caffe/tools/convert_annoset.cpp \
    ../ssd-caffe/tools/convert_imageset.cpp \
    ../ssd-caffe/tools/create_label_map.cpp \
    ../ssd-caffe/tools/device_query.cpp \
    ../ssd-caffe/tools/extract_features.cpp \
    ../ssd-caffe/tools/finetune_net.cpp \
    ../ssd-caffe/tools/get_image_size.cpp \
    ../ssd-caffe/tools/net_speed_benchmark.cpp \
    ../ssd-caffe/tools/test_net.cpp \
    ../ssd-caffe/tools/train_net.cpp \
    ../ssd-caffe/tools/upgrade_net_proto_binary.cpp \
    ../ssd-caffe/tools/upgrade_net_proto_text.cpp \
    ../ssd-caffe/tools/upgrade_solver_proto_text.cpp

INCLUDEPATH += "/data/Projects/pro_caffe/ssd-caffe/include/"
INCLUDEPATH += "/usr/include/hdf5/serial/"
